name = "SimpleTopOpt"
uuid = "4972e784-d3e6-4114-81a0-30adeade70b8"
authors = ["mjachi <mmmeeeker@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
